version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/code/frontend/src
      - ./frontend/public:/code/frontend/public
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: 
      context: ./backend
    command: npm run start -- --host 0.0.0.0
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/code/backend/src